Repository bcgov/CITZ-HybridWorkplace, pull requests merged in 2022-06, with the labels that each got.

#179 Added max-lines to ESLint, created swagger-conf.js
  .eslintrc.json
  app/server/express.js
  app/server/swagger-conf.js
Labels: swagger, eslint

#184 authenticateToken.js was missing return
  app/server/middleware/authenticateToken.js
Labels: bugfix

#186 HWP-291 Add Joining/Leaving community functionality in frontend
  app/client/src/components/communitiesList.js
  app/client/src/components/createCommunity.js
  app/client/src/components/joinButton.js
  app/client/src/components/joinCommunitiesList.js
  app/client/src/components/usersCommunitiesList.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/views/home.js
  app/client/src/views/profilePage.js
Labels: frontend, redux

#187 Removing duplicate code from usersCommunitiesList.js
  app/client/src/components/usersCommunitiesList.js
Labels: enhancement, frontend

#188 Post Modal only lists community the user is a part of
  app/client/src/components/modals/addPostModal.js
Labels: frontend, redux

#189 HWP-309 Handle Unauthorized Access to Pages
  app/client/src/privateComponent.js
  app/client/src/routes.js
Labels: frontend, Security

#185 Hwp 330 create files for user tests
  app/server/package.json
  app/server/tests/api-deleteUser.test.js
  app/server/tests/api-getUser.test.js
  app/server/tests/api-patchUser.test.js
  app/server/tests/api-register.test.js
  app/server/tests/functions/userFunctions.js
Labels: jest

#191 HWP-351 Add frontend post flagging functionality
  app/client/src/App.js
  app/client/src/components/alertList.js
  app/client/src/components/modals/flagPostModal.js
  app/client/src/components/post.js
  app/client/src/components/postsList.js
  app/client/src/layout/footer.js
  app/client/src/redux/ducks/flagDuck.js
  app/client/src/redux/index.js
Labels: frontend, redux

#194 Matching frontend variable names with backend
  app/client/src/components/editProfile.js
  app/client/src/components/modals/addPostModal.js
  app/client/src/components/profileInfo.js
  app/client/src/redux/ducks/authDuck.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/flagDuck.js
  app/client/src/redux/ducks/profileDuck.js
  app/client/src/views/login.js
  app/client/src/views/register.js
Labels: refactor, frontend

#193 HWP-300: Comment edit history and timestamps
  app/server/middleware/generateRefreshToken.js
  app/server/middleware/generateToken.js
  app/server/models/comment.model.js
  app/server/models/community.model.js
  app/server/models/post.model.js
  app/server/models/user.model.js
  app/server/package-lock.json
  app/server/package.json
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityFlags.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/community/communityRules.js
  app/server/routes/v1/community/communityTags.js
  app/server/routes/v1/login.js
  app/server/routes/v1/logout.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/post/postFlags.js
  app/server/routes/v1/post/postTags.js
  app/server/routes/v1/register.js
  app/server/routes/v1/token.js
  app/server/routes/v1/user.js
Labels: backend

#196 HWP-358: Fixed delete post not actually deleting
  app/server/routes/v1/post/post.js
Labels: backend, bugfix

#195 Only show sidebar if logged in
  app/client/src/layout/header.js
  app/client/src/privateComponent.js
  app/client/src/routes.js
  app/client/src/views/404Page.js
Labels: frontend

#198 HWP-316: Comment replys api
  app/server/express.js
  app/server/models/comment.model.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/comment/commentReply.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/user.js
  app/server/swagger-conf.js
Labels: backend

#199 HWP-362: Added availableTags to post schema
  app/server/models/post.model.js
  app/server/routes/v1/community/communityTags.js
Labels: backend

#200 HWP-287 Post Deletion
  app/client/src/components/modals/deletePostModal.js
  app/client/src/components/modals/flagPostModal.js
  app/client/src/components/post.js
  app/client/src/components/postsList.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/redux/index.js
Labels: frontend, redux

#202 HWP-306: Order communities by engagement option
  .env-template
  app/server/models/user.model.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/comment/commentReply.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/register.js
  docker-compose.yaml
Labels: backend

#203 Post creation includes availabaleTags
  app/server/routes/v1/post/post.js
Labels: backend

#201 HWP-312: Comment voting
  app/server/express.js
  app/server/models/comment.model.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/comment/commentReply.js
  app/server/routes/v1/comment/commentVoting.js
  app/server/swagger-conf.js
Labels: backend

#204 Fixed GET /api/post checking for communities user is a part of
  app/server/routes/v1/comment/commentVoting.js
  app/server/routes/v1/post/post.js
Labels: backend, bugfix

#205 Fixes getting user's communities.community
  app/server/middleware/generateToken.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityMembers.js
Labels: backend, bugfix

#206 Modified community.js to allow for tags upon community creation
  app/server/routes/v1/community/community.js
Labels: backend

#207 HWP-288 Frontend Tagging
  app/client/package.json
  app/client/src/components/createCommunity.js
  app/client/src/components/joinButton.js
  app/client/src/components/post.js
  app/client/src/components/postsList.js
  app/client/src/components/tag.js
  app/client/src/components/tagsList.js
  app/client/src/redux/ducks/authDuck.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
Labels: frontend, redux

#209 Updating API Environment Variables
  openshift/templates/api-dc.yaml
Labels: openshift

#215 HWP-365 Added post tag tests. Cleaned up functions.
  app/server/tests/api-deletePostTags.test.js
  app/server/tests/api-getPostTags.test.js
  app/server/tests/api-postPostTags.test.js
  app/server/tests/functions/communityFunctions.js
  app/server/tests/functions/postFunctions.js
Labels: jest

#216 HWP-383 - Update Existing Test files to follow Test Matrix
  app/server/jest.config.js
  app/server/tests/api-deleteCommunity.test.js
  app/server/tests/api-getCommunitiesByTitle.test.js
  app/server/tests/api-getCommunity.test.js
  app/server/tests/functions/communityFunctions.js
Labels: jest

#217 HWP-361: API response error handling
  app/server/express.js
  app/server/middleware/authenticateToken.js
  app/server/middleware/sanitizeInputs.js
  app/server/package-lock.json
  app/server/package.json
  app/server/responseError.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/comment/commentReply.js
  app/server/routes/v1/comment/commentVoting.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityFlags.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/community/communityRules.js
  app/server/routes/v1/community/communityTags.js
  app/server/routes/v1/login.js
  app/server/routes/v1/logout.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/post/postFlags.js
  app/server/routes/v1/post/postTags.js
  app/server/routes/v1/register.js
  app/server/routes/v1/token.js
  app/server/routes/v1/user.js
Labels: refactor, backend

#208 Hwp 349 - Build Functional Profile Page
  app/client/package-lock.json
  app/client/package.json
  app/client/src/App.jsx
  app/client/src/Routes.jsx
  app/client/src/components/ProfileInfo.jsx
  app/client/src/layout/Footer.jsx
  app/client/src/layout/Header.jsx
  app/client/src/layout/SideMenu.jsx
  app/client/src/layout/footer.css
  app/client/src/layout/header.css
  app/client/src/layout/sideMenu.css
  app/client/src/redux/ducks/authDuck.js
  app/client/src/redux/ducks/profileDuck.js
  app/client/src/views/ProfilePage.jsx
Labels: frontend

#219 HWP-286 Creator of community can delete community
  app/client/src/components/CommunitiesList.jsx
  app/client/src/components/Community.jsx
  app/client/src/components/modals/DeleteCommunityModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/modalDuck.js
Labels: frontend, redux

#223 Hwp 349 - Build Functional Profile Page
  app/client/README.md
  app/client/src/components/ProfileInfo.jsx
  app/client/src/redux/ducks/authDuck.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/views/ProfilePage.jsx
Labels: documentation, frontend

#218 HWP-366 Adding initial post flag tests
  app/server/tests/api-deletePostFlags.test.js
  app/server/tests/api-deletePostTags.test.js
  app/server/tests/api-getPostFlags.test.js
  app/server/tests/api-getPostTags.test.js
  app/server/tests/api-postPostFlags.test.js
  app/server/tests/api-postPostTags.test.js
  app/server/tests/functions/communityFunctions.js
  app/server/tests/functions/postFunctions.js
Labels: jest

#225 Hwp 370 - Create API tests for Community Rules
  app/server/tests/api-deleteCommunity.test.js
  app/server/tests/api-deletePost.test.js
  app/server/tests/api-deletePostFlags.test.js
  app/server/tests/api-deletePostTags.test.js
  app/server/tests/api-getCommunitiesByTitle.test.js
  app/server/tests/api-getCommunity.test.js
  app/server/tests/api-getCommunityRules.test.js
  app/server/tests/api-getPost.test.js
  app/server/tests/api-getPostFlags.test.js
  app/server/tests/api-getPostTags.test.js
  app/server/tests/api-patchPost.test.js
  app/server/tests/api-postPost.test.js
  app/server/tests/api-postPostFlags.test.js
  app/server/tests/api-postPostTags.test.js
  app/server/tests/api-setCommunityRules.test.js
  app/server/tests/functions/communityFunctions.js
Labels: jest

#227 HWP-390: Fix for refresh token saving to database
  app/server/routes/v1/login.js
  app/server/routes/v1/logout.js
Labels: backend, bugfix

#222 Zach axios instance
  app/client/src/axiosInstance.js
  app/client/src/components/PrivateComponent.jsx
  app/client/src/redux/ducks/authDuck.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/redux/ducks/profileDuck.js
  app/client/src/store.js
  app/client/src/views/HomePage.jsx
Labels: frontend, redux

#220 HWP-346: Reusable api functions
  app/server/functions/checkPatchQuery.js
  app/server/functions/checkUserIsMemberOfCommunity.js
  app/server/functions/findSingleDocuments.js
  app/server/functions/updateCommunityEngagement.js
  app/server/middleware/sanitizeInputs.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/comment/commentReply.js
  app/server/routes/v1/comment/commentVoting.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityFlags.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/community/communityRules.js
  app/server/routes/v1/community/communityTags.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/post/postFlags.js
  app/server/routes/v1/post/postTags.js
  app/server/routes/v1/user.js
Labels: refactor, backend

#226 Hwp 369 - Create API test for Community Tags
  app/server/tests/api-createCommunity.test.js
  app/server/tests/api-deleteCommunityTags.test.js
  app/server/tests/api-getCommunityTags.test.js
  app/server/tests/api-setCommunityTags.test.js
Labels: jest

#228 Hwp 368 - Create API tests for Community Flags
  app/server/jest.config.js
  app/server/tests/communityTests/api-createCommunity.test.js
  app/server/tests/communityTests/api-deleteCommunity.test.js
  app/server/tests/communityTests/api-deleteCommunityFlags.test.js
  app/server/tests/communityTests/api-deleteCommunityTags.test.js
  app/server/tests/communityTests/api-getCommunitiesByTitle.test.js
  app/server/tests/communityTests/api-getCommunity.test.js
  app/server/tests/communityTests/api-getCommunityFlags.test.js
  app/server/tests/communityTests/api-getCommunityMembers.test.js
  app/server/tests/communityTests/api-getCommunityRules.test.js
  app/server/tests/communityTests/api-getCommunityTags.test.js
  app/server/tests/communityTests/api-joinCommunity.test.js
  app/server/tests/communityTests/api-leaveCommunity.test.js
  app/server/tests/communityTests/api-patchCommunityByTitle.test.js
  app/server/tests/communityTests/api-setCommunityFlags.test.js
  app/server/tests/communityTests/api-setCommunityRules.test.js
  app/server/tests/communityTests/api-setCommunityTags.test.js
  app/server/tests/functions/communityFunctions.js
Labels: jest

#229 HWP-352 Update status codes.
  app/server/jest.config.js
  app/server/tests/api-login.test.js
  app/server/tests/communityTests/api-getCommunity.test.js
  app/server/tests/functions/postFunctions.js
  app/server/tests/postTests/api-deletePost.test.js
  app/server/tests/postTests/api-deletePostFlags.test.js
  app/server/tests/postTests/api-deletePostTags.test.js
  app/server/tests/postTests/api-getPost.test.js
  app/server/tests/postTests/api-getPostFlags.test.js
  app/server/tests/postTests/api-getPostTags.test.js
  app/server/tests/postTests/api-patchPost.test.js
  app/server/tests/postTests/api-postPost.test.js
  app/server/tests/postTests/api-postPostFlags.test.js
  app/server/tests/postTests/api-postPostTags.test.js
  app/server/tests/userTests/api-deleteUser.test.js
  app/server/tests/userTests/api-getUser.test.js
  app/server/tests/userTests/api-login.test.js
  app/server/tests/userTests/api-patchUser.test.js
  app/server/tests/userTests/api-register.test.js
Labels: jest

#231 HWP-285 Frontend Post Editing Functionality
  app/client/src/components/Post.jsx
  app/client/src/components/PostsList.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
Labels: enhancement, frontend, redux

#232 Added comment deletion functionality
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentsList.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
Labels: enhancement, frontend, redux

#235 HWP-393 Adding Logging Variable
  openshift/templates/api-dc.yaml
Labels: openshift

#233 HWP-373: API Request Logger
  .env-template
  app/server/express.js
  app/server/functions/logger.README.md
  app/server/functions/logger.js
  app/server/middleware/initLogger.js
  app/server/package-lock.json
  app/server/package.json
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/comment/commentReply.js
  app/server/routes/v1/comment/commentVoting.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityFlags.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/community/communityRules.js
  app/server/routes/v1/community/communityTags.js
  app/server/routes/v1/login.js
  app/server/routes/v1/logout.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/post/postFlags.js
  app/server/routes/v1/post/postTags.js
  app/server/routes/v1/register.js
  app/server/routes/v1/token.js
  app/server/routes/v1/user.js
  docker-compose.yaml
Labels: backend

#237 HWP-397: Fix logger setting req.body instead of copying
  app/server/middleware/initLogger.js
Labels: bugfix

#234 HWP-394: Creator name visible on comments
  app/server/models/comment.model.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/user.js
Labels: backend

#241 HWP-396 Post Tag Badges
  app/client/src/axiosInstance.js
  app/client/src/components/Tag.jsx
  app/client/src/components/TagsList.jsx
Labels: frontend

#239 HWP-395: Community page
  app/client/src/Routes.jsx
  app/client/src/components/Community.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#242 HWP-400: Fixed community not being added to user document
  app/server/routes/v1/community/community.js
Labels: backend, bugfix

#245 HWP-363-and-381: Organization and interests added to user schema
  app/server/models/user.model.js
Labels: backend, mongo

#243 HWP-377: Backend user post count
  app/server/models/user.model.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/register.js
  app/server/routes/v1/user.js
Labels: backend

#244 HWP-377: Frontend user post count
  app/client/src/components/ProfileInfo.jsx
Labels: frontend

#246 HWP-405 Community page only display posts in that community
  app/client/src/components/PostsList.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/PostsPage.jsx
Labels: frontend, bugfix

#247 HWP-401: Backend - Added commentCount and creatorName to post
  app/server/models/post.model.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/user.js
Labels: backend

#249 HWP-407: Bug fixed in comment.js route checkPatchQuery() parameters
  app/server/routes/v1/comment/comment.js
Labels: backend, bugfix

#248 HWP-401: Frontend - Show community, creator name, and comment count on posts
  app/client/src/components/Post.jsx
  app/client/src/components/SingularPost.jsx
Labels: frontend

#253 HWP-409: Post and post page styling
  app/client/package-lock.json
  app/client/package.json
  app/client/src/components/Post.jsx
  app/client/src/components/SingularPost.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#250 Added modify community functionality
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend, redux

#255 HWP-411 - Logout page
  app/client/src/Routes.jsx
  app/client/src/views/LogoutPage.jsx
Labels: frontend

#254 HWP-410 Text that redirects uses cursor pointer
  app/client/src/components/Community.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#256 HWP-412 Eliminate frontend errors/warnings
  app/client/package-lock.json
  app/client/package.json
  app/client/src/Routes.jsx
  app/client/src/components/AlertList.jsx
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentsList.jsx
  app/client/src/components/CommunitiesList.jsx
  app/client/src/components/Community.jsx
  app/client/src/components/CreateCommunity.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/PostsList.jsx
  app/client/src/components/ProfileInfo.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/components/modals/DeleteCommunityModal.jsx
  app/client/src/components/modals/DeletePostModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/components/modals/FlagPostModal.jsx
  app/client/src/layout/Footer.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/ProfilePage.jsx
Labels: enhancement, frontend

#257 HWP-404: Backend - creatorName, memberCount, and latestActivity to community
  app/server/express.js
  app/server/models/community.model.js
  app/server/routes/v1/comment/comment.js
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/community/communityRules.js
  app/server/routes/v1/community/communityTags.js
  app/server/routes/v1/post/post.js
  app/server/routes/v1/register.js
  app/server/routes/v1/user.js
Labels: backend

#258 HWP-404: Frontend - Community Enhancements
  app/client/src/components/Community.jsx
  app/client/src/components/JoinButton.jsx
  app/client/src/components/SingularPost.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/ProfilePage.jsx
  mongo/init/data/communities.json
Labels: frontend

#262 Avatar profile link
  app/client/src/layout/Header.jsx
Labels: enhancement, frontend

#263 Adjusts community tile sizing
  app/client/src/views/ProfilePage.jsx
Labels: refactor, frontend

#264 Styling refactor
  app/client/src/components/CommunitiesList.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
Labels: refactor, frontend

#268 HWP-299 Added reply functionality
  app/client/src/Routes.jsx
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentRepliesList.jsx
  app/client/src/components/CommentReply.jsx
  app/client/src/components/CreateComment.jsx
  app/client/src/components/Post.jsx
  app/client/src/redux/ducks/postDuck.js
  app/client/src/views/LoadingPage.jsx
  app/client/src/views/PostPage.jsx
Labels: enhancement, frontend

#266 HWP-415: Fixed comment edit showing wrong date
  app/client/src/components/Comment.jsx
Labels: frontend, bugfix

#271 HWP-419 Updated About Page
  app/client/src/views/AboutPage.jsx
Labels: frontend

#270 HWP-420: Added information to the community page sidebar
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#272 HWP-417 UI Tweaks
  app/client/src/components/Post.jsx
  app/client/src/layout/Header.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/ProfilePage.jsx
Labels: enhancement, frontend

#273 Styling tweaks
  app/client/src/App.css
  app/client/src/components/Post.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/PostPage.jsx
  app/client/src/views/ProfilePage.jsx
Labels: frontend

#274 HWP-422: Fixed creatorName not being set on comment reply
  app/server/routes/v1/comment/commentReply.js
Labels: backend, bugfix

#280 HWP- : LoadingButton Component Override
  app/client/src/App.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#279 Fixed Bugs
  app/client/src/components/CommunitiesList.jsx
  app/client/src/components/JoinButton.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/modals/DeletePostModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/PostPage.jsx
Labels: frontend, bugfix

#281 Homepage at root URL
  app/client/src/Routes.jsx
  app/client/src/components/CreateCommunity.jsx
  app/client/src/components/GuestOnlyComponent.jsx
  app/client/src/layout/Header.jsx
  app/client/src/layout/SideMenu.jsx
  app/client/src/views/LoginPage.jsx
Labels: enhancement, frontend

#284 HWP-313 Added comment flagging functionality
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentsList.jsx
  app/client/src/components/modals/FlagCommentModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
Labels: frontend, redux

#285 HWP-427: Fixed post tagging
  app/server/routes/v1/post/postTags.js
Labels: backend

#287 Incorrect Tag Badge Number Fix
  app/client/src/components/GuestOnlyComponent.jsx
  app/client/src/components/TagsList.jsx
Labels: frontend, bugfix

#283 HWP-424: Required modal fields
  app/client/src/Routes.jsx
  app/client/src/components/CreateComment.jsx
  app/client/src/components/CreateCommunity.jsx
  app/client/src/components/SingularPost.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#291 HWP-435 Post Body Markdown
  app/client/package-lock.json
  app/client/package.json
  app/client/src/components/Post.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
Labels: enhancement, frontend

#288 HWP-372 apply matrix to register
  app/server/routes/v1/register.js
  app/server/tests/functions/authFunctions.js
  app/server/tests/functions/randomizer.js
  app/server/tests/userTests/api-register.test.js
Labels: jest

#292 HWP-447 and HWP-438
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/components/modals/DeletePostModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/components/modals/FlagCommentModal.jsx
  app/client/src/components/modals/FlagPostModal.jsx
  app/client/src/components/modals/addPost.css
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
Labels: enhancement, refactor, frontend

#297 HWP-375 Added maintenance page
  app/client/src/Routes.jsx
  app/client/src/helperFunctions/isAPIHealthy.js
  app/client/src/views/APIDownPage.jsx
  app/client/src/views/LoadingPage.jsx
Labels: frontend

#296 HWP 386 api test documentation
  app/server/tests/communityTests/api-getCommunityMembers.test.js
  app/server/tests/communityTests/api-joinCommunity.test.js
  app/server/tests/communityTests/api-leaveCommunity.test.js
  app/server/tests/functions/authFunctions.js
  app/server/tests/functions/communityFunctions.js
  app/server/tests/functions/postFunctions.js
  app/server/tests/functions/userFunctions.js
Labels: jest

#303 HWP-445: (Frontend) New Community Digest
  app/client/src/components/CommunitiesList.jsx
  app/client/src/components/Community.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#302 HWP-445 & HWP-444: New community digest & Registration email
  .env-template
  app/server/db.js
  app/server/dbInit/optionsCollection.js
  app/server/functions/bulkNotify.js
  app/server/jobs/newCommunitiesDigestDaily.js
  app/server/models/user.model.js
  app/server/package-lock.json
  app/server/package.json
  app/server/routes/v1/community/community.js
  app/server/routes/v1/community/communityMembers.js
  app/server/routes/v1/register.js
  app/server/routes/v1/user.js
  docker-compose.yaml
Labels: backend, gcNotify

#305 HWP-379: Optional username query to GET API/POST
  app/server/routes/v1/post/post.js
Labels: backend

#306 HWP-382: Order communities by latestActivity
  app/server/routes/v1/community/community.js
  docker-compose.yaml
Labels: backend
