Repository bcgov/CITZ-HybridWorkplace, pull requests merged in 2022-07, with the labels that each got.

#307 HWP-441: Fixed regex for input validation
  app/server/db.js
  app/server/dbInit/optionsCollection.js
  app/server/express.js
  docker-compose.yaml
Labels: backend, bugfix

#309 Backend Keycloak Implementation
  .env-template
  app/client/package-lock.json
  app/client/package.json
  app/server/express.js
  app/server/models/user.model.js
  app/server/package-lock.json
  app/server/package.json
  app/server/routes/v1/keycloakLogin.js
Labels: backend

#310 Infinite Loop Fix
  app/client/src/components/CommunitiesList.jsx
Labels: frontend, bugfix

#308 HWP-452: Updated got in app/server
  app/server/package-lock.json
  app/server/package.json
Labels: dependencies

#313 Website Metadata Update
  app/client/public/favicon.ico
  app/client/public/index.html
  app/client/public/logo192.jpg
  app/client/public/logo192.png
  app/client/public/logo512.jpg
  app/client/public/logo512.png
  app/client/public/logo758.jpg
  app/client/public/manifest.json
Labels: frontend

#312 HWP-426 Create Splash Page
  app/client/src/App.jsx
  app/client/src/Routes.jsx
  app/client/src/index.css
  app/client/src/layout/icons/BC-government-logo-NEW.jpg
  app/client/src/redux/ducks/authDuck.js
  app/client/src/views/LoginPage.jsx
  app/client/src/views/Styles/login.css
Labels: frontend

#315 HWP-457: Added avatar field and changed organization field in user
  app/server/versions/v1/db/init/optionsCollection.js
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/models/user.model.js
  app/server/versions/v1/routes/keycloakLogin.js
  app/server/versions/v1/routes/user.js
Labels: backend

#323 Hwp 449 fix community tests to follow new standards
  app/server/versions/v1/tests/communityTests/api-createCommunity.test.js
  app/server/versions/v1/tests/communityTests/api-deleteCommunity.test.js
  app/server/versions/v1/tests/communityTests/api-deleteCommunityFlags.test.js
  app/server/versions/v1/tests/communityTests/api-deleteCommunityTags.test.js
  app/server/versions/v1/tests/communityTests/api-getCommunitiesByTitle.test.js
  app/server/versions/v1/tests/communityTests/api-getCommunity.test.js
  app/server/versions/v1/tests/communityTests/api-getCommunityFlags.test.js
  app/server/versions/v1/tests/communityTests/api-getCommunityMembers.test.js
  app/server/versions/v1/tests/communityTests/api-getCommunityRules.test.js
  app/server/versions/v1/tests/communityTests/api-getCommunityTags.test.js
  app/server/versions/v1/tests/communityTests/api-joinCommunity.test.js
  app/server/versions/v1/tests/communityTests/api-leaveCommunity.test.js
  app/server/versions/v1/tests/communityTests/api-patchCommunityByTitle.test.js
  app/server/versions/v1/tests/communityTests/api-setCommunityFlags.test.js
  app/server/versions/v1/tests/communityTests/api-setCommunityRules.test.js
  app/server/versions/v1/tests/communityTests/api-setCommunityTags.test.js
  app/server/versions/v1/tests/functions/communityFunctions.js
Labels: jest

#327 Fixed get user missing fields
  app/server/versions/v1/routes/user.js
Labels: backend, bugfix

#326 Linkage Additions
  app/client/src/components/Comment.jsx
  app/client/src/components/Post.jsx
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#328 HWP-296 Comment Upvoting/Downvoting
  app/client/src/components/Comment.jsx
  app/client/src/components/Tag.jsx
  app/client/src/redux/ducks/postDuck.js
Labels: frontend

#325 HWP-462: (Frontend) Updated community rules and tags
  app/client/src/components/Tag.jsx
  app/client/src/components/TagsList.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#314 HWP-421: Overhaul Profile Page & Associated Components
  app/client/package-lock.json
  app/client/package.json
  app/client/src/App.jsx
  app/client/src/components/Community.jsx
  app/client/src/components/JoinButton.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/ProfileInfo.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditUserBioModal.jsx
  app/client/src/components/modals/EditUserInfoModal.jsx
  app/client/src/components/modals/EditUserInterestsModal.jsx
  app/client/src/components/modals/SettingsModal.jsx
  app/client/src/layout/Header.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/redux/ducks/profileDuck.js
  app/client/src/redux/index.js
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/ProfilePage.jsx
  app/server/package-lock.json
  docker-compose.yaml
  package-lock.json
Labels: enhancement, frontend, redux

#334 Added Darkmode to Settings
  app/client/src/App.jsx
  app/client/src/components/modals/SettingsModal.jsx
  app/client/src/theme.js
Labels: frontend

#339 HWP-485
  app/client/src/components/GuestOnlyComponent.jsx
  app/client/src/components/PrivateComponent.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend, bugfix

#336 HWP-486: Fixed gcNotify on Keycloak register
  app/server/express.js
  app/server/versions/v1/routes/keycloakLogin.js
Labels: backend, bugfix

#337 Bio, Interests, and Notification Frequency
  app/client/src/components/ProfileInfo.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditUserBioModal.jsx
  app/client/src/components/modals/EditUserInfoModal.jsx
  app/client/src/components/modals/EditUserInterestsModal.jsx
  app/client/src/components/modals/SettingsModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/profileDuck.js
  app/client/src/theme.js
  app/client/src/views/ProfilePage.jsx
Labels: enhancement, frontend, redux

#341 Backend Moderators
  app/server/express.js
  app/server/versions/v1/authorization/communityAuthorization.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/community/communityMembers.js
  app/server/versions/v1/routes/community/communityModerators.js
  app/server/versions/v1/routes/community/communityRules.js
  app/server/versions/v1/routes/community/communityTags.js
  app/server/versions/v1/routes/routeImports.js
Labels: backend

#342 Frontend Error Removal
  app/client/src/Routes.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/components/modals/DeleteCommunityModal.jsx
  app/client/src/components/modals/DeletePostModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/components/modals/EditUserBioModal.jsx
  app/client/src/components/modals/EditUserInfoModal.jsx
  app/client/src/components/modals/EditUserInterestsModal.jsx
  app/client/src/components/modals/FlagCommentModal.jsx
  app/client/src/components/modals/FlagPostModal.jsx
  app/client/src/components/modals/SettingsModal.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/RegisterPage.jsx
Labels: frontend

#338 HWP-372 apply testing matrix
  app/server/versions/v1/tests/api-health.test.js
  app/server/versions/v1/tests/functions/randomizer.js
  app/server/versions/v1/tests/functions/userFunctions.js
  app/server/versions/v1/tests/postTests/api-deletePost.test.js
  app/server/versions/v1/tests/postTests/api-deletePostFlags.test.js
  app/server/versions/v1/tests/postTests/api-deletePostTags.test.js
  app/server/versions/v1/tests/postTests/api-getPost.test.js
  app/server/versions/v1/tests/postTests/api-getPostFlags.test.js
  app/server/versions/v1/tests/postTests/api-getPostTags.test.js
  app/server/versions/v1/tests/postTests/api-patchPost.test.js
  app/server/versions/v1/tests/postTests/api-postPost.test.js
  app/server/versions/v1/tests/postTests/api-postPostFlags.test.js
  app/server/versions/v1/tests/postTests/api-postPostTags.test.js
  app/server/versions/v1/tests/userTests/api-deleteUser.test.js
  app/server/versions/v1/tests/userTests/api-getUser.test.js
  app/server/versions/v1/tests/userTests/api-login.test.js
  app/server/versions/v1/tests/userTests/api-patchUser.test.js
  app/server/versions/v1/tests/userTests/api-register.test.js
Labels: jest

#335 HWP-125: (Backend) Profile avatar changes
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/models/user.model.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentReply.js
  app/server/versions/v1/routes/user.js
Labels: backend

#347 HWP-125: (Frontend) Profile avatar + voting style tweak
  app/client/src/components/AvatarIcon.jsx
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentReply.jsx
  app/client/src/components/CreateComment.jsx
  app/client/src/components/modals/EditAvatarModal.jsx
  app/client/src/images/avatar/profile-icon-vector-150x150.jpg
  app/client/src/layout/Header.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/profileDuck.js
  app/client/src/redux/ducks/userDuck.js
  app/client/src/redux/index.js
  app/client/src/views/APIDownPage.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/ProfilePage.jsx
  app/server/versions/v1/routes/user.js
Labels: frontend, redux

#349 HWP-125: (Backend) Avatar fixes
  app/server/versions/v1/models/comment.model.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/models/post.model.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentReply.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/post/post.js
Labels: backend, bugfix

#348 Updated visuals for darkmode
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentRepliesList.jsx
  app/client/src/components/CommentReply.jsx
  app/client/src/components/CreateComment.jsx
  app/client/src/components/MarkDownEditor.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/ProfileInfo.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/components/modals/SettingsModal.jsx
  app/client/src/layout/Header.jsx
  app/client/src/theme.js
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
Labels: frontend, bugfix

#353 Frontend Tweaks
  app/client/src/layout/Header.jsx
  app/client/src/layout/icons/404.png
  app/client/src/views/Page404.jsx
Labels: frontend

#351 compose env fix, readme update
  .github/workflows/build-deploy-hwp-api.yaml
  README.md
  docker-compose.yaml
Labels: documentation, docker

#354 Fixed Darkmode Bugs
  app/client/src/components/CommentReply.jsx
  app/client/src/layout/Header.jsx
Labels: frontend, bugfix

#355 HWP-304 & 475: (Backend) Add/remove/permissions moderators & hidden posts/comments
  app/server/swagger/tags.js
  app/server/versions/v1/functions/auth/communityAuthorization.js
  app/server/versions/v1/functions/getCreatorName.js
  app/server/versions/v1/functions/getFullName.js
  app/server/versions/v1/functions/validateCommunityInputs.js
  app/server/versions/v1/functions/validatePostInputs.js
  app/server/versions/v1/models/comment.model.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/models/post.model.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentReply.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/community/communityMembers.js
  app/server/versions/v1/routes/community/communityModerators.js
  app/server/versions/v1/routes/community/communityRules.js
  app/server/versions/v1/routes/community/communityTags.js
  app/server/versions/v1/routes/post/post.js
  app/server/versions/v1/routes/post/postTags.js
  app/server/versions/v1/routes/user.js
Labels: backend, mongo

#356 Undefined Community Name Fix
  app/server/versions/v1/routes/community/community.js
Labels: backend, bugfix

#350 HWP-125: (Frontend) Avatar fixes + Profile tweaks
  app/client/src/components/AvatarIcon.jsx
  app/client/src/components/Comment.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/ProfileInfo.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/ProfilePage.jsx
Labels: frontend, bugfix

#357 HWP-488: Fixes for profile title, ministry and bio
  app/client/src/Routes.jsx
  app/client/src/components/EditProfile.jsx
  app/client/src/components/modals/EditUserBioModal.jsx
  app/client/src/components/modals/EditUserInfoModal.jsx
  app/client/src/redux/ducks/profileDuck.js
Labels: frontend, bugfix

#359 HWP-: Interests Max Width
  app/client/src/views/ProfilePage.jsx
Labels: frontend, bugfix

#358 Bio width
  app/client/src/views/ProfilePage.jsx
Labels: frontend, bugfix

#360 HWP-304: Added moderators list to community page
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#362 Fix moderator edit post and comment
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/post/post.js
Labels: backend, bugfix

#363 HWP-475: Hidden and pinned posts
  app/client/src/components/Comment.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/redux/ducks/postDuck.js
Labels: frontend

#364 Hwp 473 moderator view
  app/client/src/components/Post.jsx
  app/client/src/components/PostsList.jsx
  app/client/src/views/CommunityPage.jsx
Labels: enhancement, frontend

#366 Community Redux
  app/client/src/components/CommunitiesList.jsx
  app/client/src/components/JoinButton.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/helperFunctions/communityHelpers.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/views/CommunityNotFoundPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/ProfilePage.jsx
Labels: refactor, frontend, redux

#367 Modal Action Buttons
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/components/modals/DeleteCommunityModal.jsx
  app/client/src/components/modals/DeletePostModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/components/modals/EditUserBioModal.jsx
  app/client/src/components/modals/EditUserInfoModal.jsx
  app/client/src/components/modals/EditUserInterestsModal.jsx
  app/client/src/components/modals/FlagCommentModal.jsx
  app/client/src/components/modals/FlagPostModal.jsx
  app/client/src/components/modals/SettingsModal.jsx
Labels: refactor, frontend, tweaks

#369 Fixed Edit Community Title
  app/server/versions/v1/routes/community/community.js
Labels: backend, bugfix

#368 Unable to Create Post Bug Fig
  app/client/src/components/MarkDownEditor.jsx
  app/client/src/components/modals/AddPostModal.jsx
Labels: frontend, bugfix

#370 HWP-492: Downgraded mongo version
  app/server/versions/v1/routes/comment/comment.js
  docker-compose.yaml
Labels: docker, backend, mongo

#373 Modified flaggedby array to use username
  app/server/versions/v1/models/comment.model.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/models/post.model.js
  app/server/versions/v1/routes/comment/commentFlags.js
  app/server/versions/v1/routes/community/communityFlags.js
  app/server/versions/v1/routes/post/postFlags.js
Labels: backend

#374 Bio Shows Up In EditUserBioModal.jsx
  app/client/src/components/modals/EditUserBioModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/views/ProfilePage.jsx
Labels: frontend, bugfix

#371 Fixed leave community
  app/server/versions/v1/routes/community/communityMembers.js
Labels: backend, bugfix

#379 HWP-304: Moderator permissions modal
  app/client/src/components/modals/EditModPermsModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#365 HWP-491: Kick community members
  app/server/db.js
  app/server/versions/v1/jobs/communityUnKick.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/routes/community/communityMembers.js
  app/server/versions/v1/routes/community/communityModerators.js
Labels: backend, mongo

#377 HWP-478: (Backend) Flag resolving on posts and comments
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentFlags.js
  app/server/versions/v1/routes/comment/commentReply.js
  app/server/versions/v1/routes/community/communityFlags.js
  app/server/versions/v1/routes/post/postFlags.js
Labels: backend

#361 Zach community description
  app/client/src/components/Community.jsx
  app/client/src/components/InputRuleList.jsx
  app/client/src/components/MarkDownDisplay.jsx
  app/client/src/components/MarkDownEditor.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/RuleInput.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#383 HWP-466 / HWP-468 | Promote and Demote Users
  app/client/src/components/modals/DemoteUserModal.jsx
  app/client/src/components/modals/PromoteUserModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend, redux

#372 HWP-478 Resolve Flags
  app/client/package-lock.json
  app/client/package.json
  app/client/src/components/Post.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/ResolveFlagsModal.jsx
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/moderatorDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/redux/index.js
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/PostPage.jsx
Labels: frontend

#392 HWP-493: Change data deletion in backend
  .eslintrc.json
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/functions/findCommunitiesByEngagement.js
  app/server/versions/v1/functions/findSingleDocuments.js
  app/server/versions/v1/models/comment.model.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/models/post.model.js
  app/server/versions/v1/models/user.model.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentReply.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/community/communityMembers.js
  app/server/versions/v1/routes/post/post.js
  app/server/versions/v1/routes/user.js
Labels: backend, mongo

#394 Fixed existing posts not visible
  app/server/versions/v1/db/startUp.js
Labels: backend, bugfix

#393 Fixed post edit
  app/client/src/components/modals/EditPostModal.jsx
Labels: frontend, bugfix

#396 HWP-493: Added styling to removed posts
  app/client/src/components/Post.jsx
Labels: frontend

#398 HWP-520: Changes to returned user communities in api/user
  app/server/versions/v1/functions/findCommunitiesByEngagement.js
  app/server/versions/v1/routes/user.js
Labels: backend

#400 HWP-469: Backend Search
  app/server/express.js
  app/server/swagger/tags.js
  app/server/versions/v1/routes/routeImports.js
  app/server/versions/v1/routes/search.js
Labels: backend

#401 Add Community Description to User Response
  app/server/versions/v1/routes/user.js
Labels: backend

#395 HWP-515: Added admin user
  app/server/versions/v1/classes/logger.js
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/functions/auth/communityAuthorization.js
  app/server/versions/v1/functions/auth/generateToken.js
  app/server/versions/v1/functions/checkUserIsMemberOfCommunity.js
  app/server/versions/v1/functions/findCommunitiesByEngagement.js
  app/server/versions/v1/functions/findSingleDocuments.js
  app/server/versions/v1/models/user.model.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentFlags.js
  app/server/versions/v1/routes/comment/commentReply.js
  app/server/versions/v1/routes/comment/commentVoting.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/community/communityFlags.js
  app/server/versions/v1/routes/community/communityMembers.js
  app/server/versions/v1/routes/community/communityModerators.js
  app/server/versions/v1/routes/community/communityRules.js
  app/server/versions/v1/routes/community/communityTags.js
  app/server/versions/v1/routes/keycloakLogin.js
  app/server/versions/v1/routes/login.js
  app/server/versions/v1/routes/logout.js
  app/server/versions/v1/routes/post/post.js
  app/server/versions/v1/routes/post/postFlags.js
  app/server/versions/v1/routes/post/postTags.js
  app/server/versions/v1/routes/register.js
  app/server/versions/v1/routes/token.js
  app/server/versions/v1/routes/user.js
Labels: backend

#406 Frontend moderator kick user
  app/client/docker/dev/Dockerfile
  app/client/docker/prod/Dockerfile
  app/client/src/components/modals/CommunityMembersModal.jsx
  app/client/src/components/modals/KickUserModal.jsx
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/modalDuck.js
Labels: enhancement, frontend, redux, bugfix

#399 HWP-341 Investigate Prototype Pollution in async Dependabot Vulnerability
  .github/dependabot.yaml
Labels: dependencies

#391 HWP-494 Added workflow for CodeQL scan
  .github/workflows/run-codeql-scan.yaml
Labels: Security

#397 Post Redux Refactor
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentRepliesList.jsx
  app/client/src/components/CommentReply.jsx
  app/client/src/components/CommentsList.jsx
  app/client/src/components/CreateComment.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/components/modals/EditUserInterestsModal.jsx
  app/client/src/components/modals/FlagCommentModal.jsx
  app/client/src/helperFunctions/commentHelpers.js
  app/client/src/helperFunctions/communityHelpers.js
  app/client/src/helperFunctions/postHelpers.js
  app/client/src/redux/ducks/commentDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/redux/index.js
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/PostPage.jsx
  app/client/src/views/ProfilePage.jsx
Labels: refactor, frontend, redux

#419 HWP-504 && HWP-507 | Profile Page
  app/client/src/components/Community.jsx
  app/client/src/components/ProfileInfo.jsx
  app/client/src/theme.js
  app/client/src/views/ProfilePage.jsx
Labels: frontend

#403 HWP-508: Added community resources
  app/server/versions/v1/db/init/optionsCollection.js
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/functions/validateCommunityInputs.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/routes/community/community.js
Labels: backend

#422 HWP-523: Fixed comment replies count
  app/server/versions/v1/routes/comment/comment.js
Labels: backend, bugfix

#418 HWP-522: Fixed search showing removed posts
  app/server/versions/v1/routes/search.js
Labels: backend, bugfix

#421 HWP-511: Community resources widget & Community page tweaks
  app/client/src/components/RuleInput.jsx
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#420 HWP-512: Community UI tweaks, title length, and postCount
  app/client/src/components/Community.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/server/versions/v1/db/init/optionsCollection.js
Labels: frontend

#424 Minor changes to the profile page UI. Removes a divider and creates m…
  app/client/src/components/ProfileInfo.jsx
  app/client/src/views/ProfilePage.jsx
Labels: enhancement, frontend, tweaks

#425 HWP-283: Breadcrumbs
  app/client/src/components/Croutons.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
  app/client/src/views/PostPage.jsx
Labels: enhancement, frontend

#427 Hwp 496 api moderator tests
  app/server/tests/functions/communityFunctions.js
  app/server/tests/moderationTests/api-deleteModeratorsRemove.test.js
  app/server/tests/moderationTests/api-getModerators.test.js
  app/server/tests/moderationTests/api-patchModeratorsAdd.test.js
  app/server/tests/moderationTests/api-patchModeratorsPermissions.test.js
  app/server/tests/moderationTests/api-postModeratorsKick.test.js
Labels: jest

#431 Added important values to backend search
  app/server/versions/v1/routes/search.js
Labels: backend

#407 HWP-514: Post/Community enhancements and fixes
  app/server/versions/v1/db/init/optionsCollection.js
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/functions/validateCommunityInputs.js
  app/server/versions/v1/functions/validatePostInputs.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/community/communityTags.js
  app/server/versions/v1/routes/post/post.js
Labels: backend, bugfix

#434 Removed 404 Case From Search
  app/server/versions/v1/routes/search.js
Labels: backend

#430 HWP-471 Frontend Search
  app/client/src/Routes.jsx
  app/client/src/components/Post.jsx
  app/client/src/layout/Header.jsx
  app/client/src/redux/ducks/searchDuck.js
  app/client/src/redux/index.js
  app/client/src/views/SearchPage.jsx
Labels: frontend

#435 HWP-529: Added more tooltips
  app/client/src/components/JoinButton.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#426 HWP-511: Add/Edit Community Resources + Modal Changes
  app/client/src/components/InputRuleList.jsx
  app/client/src/components/RuleInput.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/CommunityMembersModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
  app/client/src/redux/ducks/communityDuck.js
Labels: frontend

#436 HWP-509 Moderator Permissions Bug
  app/client/src/components/ModListItem.jsx
  app/client/src/components/modals/KickUserModal.jsx
  app/client/src/views/CommunityPage.jsx
Labels: frontend, bugfix

#437 HWP-530: Tweaks to about page
  app/client/src/views/AboutPage.jsx
Labels: frontend

#429 HWP-524 & 525: Allowed admin edit communities, posts, and comments + Comment edits
  app/client/src/components/Comment.jsx
  app/client/src/components/Community.jsx
  app/client/src/components/ModListItem.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/redux/ducks/commentDuck.js
  app/client/src/redux/ducks/communityDuck.js
  app/client/src/redux/ducks/postDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#432 HWP-526: creatorIsModerator on posts and comments
  app/server/versions/v1/functions/findSingleDocuments.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/community/communityMembers.js
  app/server/versions/v1/routes/post/post.js
Labels: backend

#433 HWP-527: Added moderator badge
  app/client/src/components/Comment.jsx
  app/client/src/components/Post.jsx
  app/client/src/components/modals/CommunityMembersModal.jsx
Labels: frontend

#439 Create Community With Tags Fix
  app/server/versions/v1/functions/validateCommunityInputs.js
Labels: backend, bugfix
