Repository bcgov/CITZ-HybridWorkplace, pull requests merged in 2022-08, with the labels that each got.

#438 HWP-501 Fixed Post Related Issues
  app/client/src/components/Post.jsx
  app/client/src/components/PostsList.jsx
  app/client/src/components/UsersCommunitiesList.jsx
  app/client/src/components/modals/AddPostModal.jsx
  app/client/src/components/modals/EditPostModal.jsx
  app/client/src/components/modals/ResolveFlagsModal.jsx
  app/client/src/redux/ducks/postDuck.js
  app/client/src/views/CommunityPage.jsx
Labels: frontend, bugfix

#423 Hwp 428 frontend functions
  app/client/package.json
  app/client/src/tests/functions/UserActions.js
  app/client/src/tests/system/createCommunity.e2e.test.js
Labels: jest

#405 HWP-497 Update tests.
  .github/workflows/run-tests-on-pr.yaml
  app/server/.env-test-template
  app/server/tests/README.md
  app/server/tests/commentTests/api-deleteComment.test.js
  app/server/tests/commentTests/api-getCommentReply.test.js
  app/server/tests/commentTests/api-getCommentbyId.test.js
  app/server/tests/commentTests/api-getCommentbyPost.test.js
  app/server/tests/commentTests/api-setComment.test.js
  app/server/tests/commentTests/api-setCommentReply.test.js
  app/server/tests/commentTests/api-voteOnComment.test.js
  app/server/tests/communityTests/api-createCommunity.test.js
  app/server/tests/communityTests/api-deleteCommunity.test.js
  app/server/tests/communityTests/api-deleteCommunityFlags.test.js
  app/server/tests/communityTests/api-deleteCommunityTags.test.js
  app/server/tests/communityTests/api-getCommunitiesByTitle.test.js
  app/server/tests/communityTests/api-getCommunityMembers.test.js
  app/server/tests/communityTests/api-getCommunityRules.test.js
  app/server/tests/communityTests/api-getCommunityTags.test.js
  app/server/tests/communityTests/api-joinCommunity.test.js
  app/server/tests/communityTests/api-leaveCommunity.test.js
  app/server/tests/communityTests/api-patchCommunityByTitle.test.js
  app/server/tests/communityTests/api-setCommunityFlags.test.js
  app/server/tests/communityTests/api-setCommunityRules.test.js
  app/server/tests/communityTests/api-setCommunityTags.test.js
  app/server/tests/functions/authFunctions.js
  app/server/tests/functions/commentFunctions.js
  app/server/tests/functions/communityFunctions.js
  app/server/tests/functions/postFunctions.js
  app/server/tests/functions/userFunctions.js
  app/server/tests/moderationTests/api-deleteModeratorsRemove.test.js
  app/server/tests/moderationTests/api-getModerators.test.js
  app/server/tests/moderationTests/api-patchModeratorsAdd.test.js
  app/server/tests/moderationTests/api-patchModeratorsPermissions.test.js
  app/server/tests/moderationTests/api-postModeratorsKick.test.js
  app/server/tests/postTests/api-deletePost.test.js
  app/server/tests/postTests/api-deletePostFlags.test.js
  app/server/tests/postTests/api-deletePostTags.test.js
  app/server/tests/postTests/api-getPost.test.js
  app/server/tests/postTests/api-getPostFlags.test.js
  app/server/tests/postTests/api-getPostTags.test.js
  app/server/tests/postTests/api-patchPost.test.js
  app/server/tests/postTests/api-postPost.test.js
  app/server/tests/postTests/api-postPostFlags.test.js
  app/server/tests/postTests/api-postPostTags.test.js
  app/server/tests/userTests/api-deleteUser.test.js
  app/server/tests/userTests/api-getUser.test.js
  app/server/tests/userTests/api-patchUser.test.js
Labels: jest

#440 Added online status to members list
  app/client/src/components/modals/CommunityMembersModal.jsx
  app/client/src/theme.js
Labels: frontend

#441 Added voting tooltips
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentRepliesList.jsx
  app/client/src/views/CommunityPage.jsx
Labels: frontend

#442 Fixed community modal
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/components/modals/EditCommunityModal.jsx
Labels: frontend, bugfix

#443 Fixed Overfetching in Frontend
  app/client/src/components/Post.jsx
  app/client/src/components/modals/AddCommunityModal.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/CommunityPage.jsx
  app/client/src/views/HomePage.jsx
Labels: frontend

#458 HWP-443: Added online status to profile page
  app/client/src/components/modals/CommunityMembersModal.jsx
  app/client/src/views/ProfilePage.jsx
Labels: frontend

#444 Croutons fix
  app/client/src/components/Community.jsx
  app/client/src/views/AboutPage.jsx
  app/client/src/views/CommunitiesPage.jsx
  app/client/src/views/ProfilePage.jsx
  app/client/src/views/SearchPage.jsx
Labels: frontend, bugfix

#456 HWP-470: (Backend) Admin apis
  app/server/express.js
  app/server/swagger/tags.js
  app/server/versions/v1/models/comment.model.js
  app/server/versions/v1/models/community.model.js
  app/server/versions/v1/models/post.model.js
  app/server/versions/v1/routes/admin.js
  app/server/versions/v1/routes/comment/comment.js
  app/server/versions/v1/routes/comment/commentFlags.js
  app/server/versions/v1/routes/community/community.js
  app/server/versions/v1/routes/community/communityFlags.js
  app/server/versions/v1/routes/post/post.js
  app/server/versions/v1/routes/post/postFlags.js
  app/server/versions/v1/routes/routeImports.js
  app/server/versions/v1/routes/user.js
Labels: backend

#455 HWP-470: Admin page
  app/client/src/Routes.jsx
  app/client/src/components/AdminStatusBox.jsx
  app/client/src/components/modals/AdminDeleteUserModal.jsx
  app/client/src/components/modals/AdminEditUserModal.jsx
  app/client/src/components/modals/AdminGetUserModal.jsx
  app/client/src/layout/Header.jsx
  app/client/src/redux/ducks/adminDuck.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/index.js
  app/client/src/views/AdminPage.jsx
Labels: frontend

#457 HWP-502 Comment fixes
  app/client/src/components/Comment.jsx
  app/client/src/components/CommentRepliesList.jsx
  app/client/src/components/modals/DeleteCommentModal.jsx
  app/client/src/redux/ducks/commentDuck.js
  app/client/src/redux/ducks/modalDuck.js
  app/client/src/redux/ducks/postDuck.js
Labels: frontend, redux

#460 Drops data from database
  app/server/versions/v1/db/startUp.js
Labels: DO NOT MERGE

#462 Adds admin users and fixes edit profile
  app/server/versions/v1/db/startUp.js
  app/server/versions/v1/routes/user.js
Labels: bugfix
